language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
scripts:
  - yarn build
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN  
  committer-from-gh: true
  skip-cleanup: true
  keep-history: true
  local-dir: dist
  repo: BryanPan342/bryanpan342.github.io
  target-branch: master
  on:
    branch: master